<a href="https://colab.research.google.com/github/Veda-18v/DS-INTERNSHIP/blob/main/DS_DAY_2_LIBRARIES.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a[0])


[1 2 3 4 5]


In [ ]:
import numpy as np
a = np.array([[1,2,3,4],[9,10,11,12]])
b = np.array([[5,6,7,8],[13,14,15,16]])
c = np.concatenate((a,b))
d = np.concatenate((a,b),axis=1)
print(c)
print(d)

[[ 1  2  3  4]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [13 14 15 16]]
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]


In [6]:
import numpy as np
a= np.array([3,5,6,2,9,8,7,1,4])
b= np.sort(a)
print(b)

[1 2 3 4 5 6 7 8 9]


In [11]:
arr=np.array([[1,2,3,4,5], [6,7,8,9,10],[11,12,13,14,15]])
b =np.array([[1],[2],[3]])
c=arr + b
print(c)

[[ 2  3  4  5  6]
 [ 8  9 10 11 12]
 [14 15 16 17 18]]


In [17]:
import pandas as pd
a= pd.Series(["BMW","Toyota","Honda"])
print(a)

0       BMW
1    Toyota
2     Honda
dtype: object


In [19]:
a= pd.DataFrame({"BMW","Toyota","Honda"})
a

0
0   Honda
1  Toyota
2     BMW